version: '3.1'

services:
    # db:
    #     image: mysql
    #     command: --default-authentication-plugin=mysql_native_password
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: 123456
    #         MYSQL_DATABASE: kuser
    #         MYSQL_USER: kuser
    #         MYSQL_PASSWORD: 123456
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456
            MONGO_INITDB_DATABASE: user
        ports: 
            - "27017:27017"
    builder:
        build: 
            context: ./
            dockerfile: Dockerfile
    user-mgmt:
        build: 
            context: ./
            dockerfile: ./service/user-mgmt/Dockerfile
        links: 
            - "mongo"
        environment: 
            DB_NAME: user
            DB_PASSWORD: 123456
            DB_USERNAME: root
            DB_HOST: mongo
            DB_PORT: 27017
