version: '3.1'

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: kuser
            MYSQL_USER: kuser
            MYSQL_PASSWORD: 123456
    builder:
        build: 
            context: ./
            dockerfile: Dockerfile
    user-mgmt:
        build: 
            context: ./
            dockerfile: ./service/user-mgmt/Dockerfile
